INSERT INTO COMPANY_ENTITY (COMPANY_ID , COMPANY_BOARD_OF_DIRECTORS, COMPANY_BRIEF_WRITE_UP,
 COMPANYCEO, COMPANY_NAME, COMPANY_SECTOR, COMPANY_TURNOVER)
 VALUES(1,'Polamreddy Group','Emerging company',
 'Polamreddy Vivek Reddy','The Good Tech Company','Service','24,000,000');
 
 INSERT INTO COMPANY_ENTITY (COMPANY_ID , COMPANY_BOARD_OF_DIRECTORS, COMPANY_BRIEF_WRITE_UP,
 COMPANYCEO, COMPANY_NAME, COMPANY_SECTOR, COMPANY_TURNOVER)
 VALUES(2,'The Social Impact Company','Emerging company',
 'JSGV Reddy','The_Social_Company','Banking','94,000,000');

 
 
 
 
 INSERT INTO COMPANY_IPO_ENTITY (COMPANY_IPO_ID ,  COMPANY_IPO_NAME, COMPANY_IPO_SHARES,
 COMPANY_IPO_STOCK_EXCHANGE, COMPANY_IPO_TURNOVER)
 VALUES(1,'The Good Tech Company','12,000',
 'NSE','24,000,000');
 
  INSERT INTO COMPANY_IPO_ENTITY (COMPANY_IPO_ID ,  COMPANY_IPO_NAME, COMPANY_IPO_SHARES,
 COMPANY_IPO_STOCK_EXCHANGE, COMPANY_IPO_TURNOVER)
 VALUES(2,'The Social Impact Company','62,000',
 'BSE','94,000,000');
 
 